#!/usr/bin/env python3
"""Build static ASPEC case-study cards and published detail pages."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "case-studies.json"
PORTFOLIO_PATH = ROOT / "portfolio.html"
TEMPLATE_PATH = ROOT / "templates" / "case-study-template.html"
PROCESS_TEMPLATE_PATH = ROOT / "templates" / "case-study-process-template.html"
OUTPUT_DIR = ROOT / "case-studies"
SITEMAP_PATH = ROOT / "sitemap.xml"

CARD_START = "<!-- CASE_STUDIES:START -->"
CARD_END = "<!-- CASE_STUDIES:END -->"
SITEMAP_START = "<!-- CASE_STUDIES:START -->"
SITEMAP_END = "<!-- CASE_STUDIES:END -->"
GENERATED_MARKER = "<!-- GENERATED BY scripts/build-case-studies.py -->"

VALID_CATEGORIES = {"ai", "ocr", "barcode", "robot", "alignment", "software", "optics"}
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
SUMMARY_LABELS = {
    "industry": "산업",
    "inspectionTarget": "검사 대상",
    "inspectionPurpose": "검사 목적",
    "camera": "카메라",
    "lens": "렌즈",
    "lighting": "조명",
    "software": "소프트웨어",
    "integration": "연동",
    "cycleTime": "처리속도",
}


class BuildError(RuntimeError):
    pass


def read_preserving_newlines(path: Path) -> tuple[str, str]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        content = handle.read()
    newline = "\r\n" if "\r\n" in content else "\n"
    return content, newline


def write_preserving_newlines(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(content)


def escape(value: Any) -> str:
    return html.escape(str(value), quote=True)


def load_cases() -> list[dict[str, Any]]:
    try:
        payload = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BuildError(f"Unable to read {DATA_PATH}: {exc}") from exc

    if payload.get("schemaVersion") != 1 or not isinstance(payload.get("cases"), list):
        raise BuildError("case-studies.json must contain schemaVersion=1 and a cases array")

    cases = payload["cases"]
    validate_cases(cases)
    return cases


def validate_cases(cases: list[dict[str, Any]]) -> None:
    required = {
        "slug", "published", "title", "category", "categoryLabel", "filters", "industry",
        "summary", "heroImage", "cardImage", "cardImageAlt", "keywords", "highlights",
        "technologies", "projectSummary", "overview", "problem", "difficulty", "solution",
        "inspectionMethod", "results", "images", "relatedProducts", "relatedCases",
    }
    slugs: set[str] = set()

    for index, case in enumerate(cases, start=1):
        if not isinstance(case, dict):
            raise BuildError(f"Case #{index} must be an object")
        missing = sorted(required - set(case))
        if missing:
            raise BuildError(f"Case #{index} is missing fields: {', '.join(missing)}")

        slug = case["slug"]
        if not isinstance(slug, str) or not SLUG_RE.fullmatch(slug):
            raise BuildError(f"Invalid slug for case #{index}: {slug!r}")
        if slug in slugs:
            raise BuildError(f"Duplicate slug: {slug}")
        slugs.add(slug)

        if not isinstance(case["published"], bool):
            raise BuildError(f"published must be boolean for {slug}")
        if case["category"] not in VALID_CATEGORIES:
            raise BuildError(f"Invalid category for {slug}: {case['category']}")
        if not isinstance(case["filters"], list) or not case["filters"]:
            raise BuildError(f"filters must be a non-empty array for {slug}")
        invalid_filters = set(case["filters"]) - VALID_CATEGORIES
        if invalid_filters:
            raise BuildError(f"Invalid filters for {slug}: {sorted(invalid_filters)}")

        for field in ("title", "categoryLabel", "industry", "summary", "cardImage", "cardImageAlt"):
            if not isinstance(case[field], str) or not case[field].strip():
                raise BuildError(f"{field} must not be empty for {slug}")
        for field in ("keywords", "highlights", "technologies", "results", "images", "relatedProducts", "relatedCases"):
            if not isinstance(case[field], list):
                raise BuildError(f"{field} must be an array for {slug}")
        if not isinstance(case["projectSummary"], dict):
            raise BuildError(f"projectSummary must be an object for {slug}")

        detail_template = case.get("detailTemplate", "default")
        if detail_template not in {"default", "process"}:
            raise BuildError(f"Invalid detailTemplate for {slug}: {detail_template}")
        if detail_template == "process":
            detail = case.get("processDetail")
            required_detail = {"heroSubheading", "heroDescription", "facts", "cameras", "inspectionSections", "speed", "resultCards", "engineeringIntro", "engineeringItems", "cta"}
            if not isinstance(detail, dict) or required_detail - set(detail):
                raise BuildError(f"Incomplete processDetail for {slug}")

        if case["published"]:
            publish_required = ("heroImage", "overview", "problem", "difficulty", "solution", "inspectionMethod")
            empty = [field for field in publish_required if not str(case[field]).strip()]
            if empty:
                raise BuildError(f"Published case {slug} is missing detail content: {', '.join(empty)}")
            summary = case["projectSummary"]
            if not summary.get("inspectionTarget") or not summary.get("inspectionPurpose"):
                raise BuildError(f"Published case {slug} needs inspectionTarget and inspectionPurpose")

    for case in cases:
        unknown = set(case["relatedCases"]) - slugs
        if unknown:
            raise BuildError(f"Unknown relatedCases for {case['slug']}: {sorted(unknown)}")


def render_list(items: list[str], class_name: str, label: str | None = None) -> str:
    if not items:
        return ""
    aria = f' aria-label="{escape(label)}"' if label else ""
    children = "".join(f'<li class="{class_name}">{escape(item)}</li>' for item in items)
    return f"<ul class=\"{class_name}s\"{aria}>{children}</ul>"


def render_card(case: dict[str, Any]) -> str:
    filters = " ".join(case["filters"])
    search_terms = " ".join([case["title"], case["categoryLabel"], case["industry"], case["summary"], *case["keywords"], *case["technologies"]])
    highlights = "\n".join(f'                            <li>{escape(item)}</li>' for item in case["highlights"][:3])
    tags = "\n".join(f'                            <li class="case-tag">{escape(item)}</li>' for item in case["technologies"])
    if case["published"]:
        action = f'<a class="case-action" href="case-studies/{escape(case["slug"])}.html">상세보기</a>'
    else:
        action = '<span class="case-action is-disabled" aria-disabled="true">상세 준비중</span>'

    return f'''                <article class="case-card" data-category="{escape(filters)}" data-search="{escape(search_terms.lower())}" id="case-{escape(case.get("cardId", case["slug"]))}">
                    <div class="case-media">
                        <img src="{escape(case["cardImage"])}" alt="{escape(case["cardImageAlt"])}" class="portfolio-img case-image" loading="lazy" decoding="async">
                    </div>
                    <div class="case-content">
                        <div class="case-meta">
                            <p class="case-category">{escape(case["categoryLabel"])}</p>
                            <p class="case-industry"><span>산업</span>{escape(case["industry"])}</p>
                        </div>
                        <h3 class="case-title">{escape(case["title"])}</h3>
                        <p class="case-summary">{escape(case["summary"])}</p>
                        <ul class="case-highlights" aria-label="핵심 포인트">
{highlights}
                        </ul>
                        <ul class="case-tags" aria-label="사용 기술">
{tags}
                        </ul>
                        <div class="case-card-footer">{action}</div>
                    </div>
                </article>'''


def replace_managed_block(content: str, start: str, end: str, body: str, newline: str) -> str:
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(content):
        raise BuildError(f"Managed block not found: {start}")
    block = start + newline + body.replace("\n", newline) + newline + "                " + end
    return pattern.sub(block, content, count=1)


def build_portfolio(cases: list[dict[str, Any]]) -> str:
    content, newline = read_preserving_newlines(PORTFOLIO_PATH)
    cards = ("\n\n".join(render_card(case) for case in cases)).rstrip()
    return replace_managed_block(content, CARD_START, CARD_END, cards, newline)


def text_blocks(value: str) -> str:
    parts = [part.strip() for part in re.split(r"\n\s*\n", value) if part.strip()]
    return "".join(f"<p>{escape(part)}</p>" for part in parts)


def nested_asset(path: str) -> str:
    if re.match(r"^(?:https?:)?//", path) or path.startswith("/"):
        return path
    return "../" + path


def summary_items(case: dict[str, Any]) -> str:
    values = {"industry": case["industry"], **case["projectSummary"]}
    rows = []
    for key, label in SUMMARY_LABELS.items():
        value = str(values.get(key, "")).strip()
        if value:
            rows.append(f'<div class="project-summary-item"><dt>{escape(label)}</dt><dd>{escape(value)}</dd></div>')
    return "".join(rows)


def system_items(case: dict[str, Any]) -> str:
    labels = {"camera": "Camera", "lens": "Lens", "lighting": "Lighting", "software": "Software", "integration": "Integration"}
    items = []
    for key, label in labels.items():
        value = str(case["projectSummary"].get(key, "")).strip()
        if value:
            items.append(f'<article class="system-item"><span>{label}</span><strong>{escape(value)}</strong></article>')
    return "".join(items)


def process_items(value: str) -> str:
    steps = [step.strip() for step in re.split(r"\n+", value) if step.strip()]
    return "".join(f'<li class="process-step"><span>{index:02d}</span><strong>{escape(step)}</strong></li>' for index, step in enumerate(steps, start=1))


def gallery_section(case: dict[str, Any]) -> str:
    if not case["images"]:
        return ""
    figures = []
    for image in case["images"]:
        caption = f'<figcaption>{escape(image.get("caption", ""))}</figcaption>' if image.get("caption") else ""
        figures.append(f'<figure><img src="{escape(nested_asset(image["src"]))}" alt="{escape(image["alt"])}" loading="lazy">{caption}</figure>')
    return f'''<section class="case-story-section is-alt" aria-labelledby="gallery-heading">
            <div class="case-study-inner">
                <div class="case-story-heading"><p class="case-story-index">05 · Gallery</p><h2 id="gallery-heading">실제 검사 화면 및 이미지</h2></div>
                <div class="case-gallery">{"".join(figures)}</div>
            </div>
        </section>'''


def results_section(case: dict[str, Any]) -> str:
    if not case["results"]:
        return ""
    items = "".join(f"<li>{escape(item)}</li>" for item in case["results"])
    return f'''<section class="case-story-section" aria-labelledby="results-heading">
            <div class="case-study-inner">
                <div class="case-story-heading"><p class="case-story-index">06 · Result</p><h2 id="results-heading">적용 결과</h2></div>
                <ul class="result-list">{items}</ul>
            </div>
        </section>'''


def technology_items(case: dict[str, Any]) -> str:
    items = [f"<li>{escape(item)}</li>" for item in case["technologies"]]
    for product in case["relatedProducts"]:
        items.append(f'<li><a href="{escape(nested_asset(product["url"]))}">{escape(product["name"])}</a></li>')
    return "".join(items)


def related_cases_section(case: dict[str, Any], lookup: dict[str, dict[str, Any]]) -> str:
    related = [lookup[slug] for slug in case["relatedCases"] if lookup[slug]["published"]]
    if not related:
        return ""
    cards = "".join(
        f'<a class="related-case" href="{escape(item["slug"])}.html"><span>{escape(item["categoryLabel"])}</span><strong>{escape(item["title"])}</strong></a>'
        for item in related[:3]
    )
    return f'''<section class="case-story-section is-alt" aria-labelledby="related-cases-heading">
            <div class="case-study-inner">
                <div class="case-story-heading"><p class="case-story-index">08 · Related Cases</p><h2 id="related-cases-heading">관련 구축사례</h2></div>
                <div class="related-case-grid">{cards}</div>
            </div>
        </section>'''

def process_fact_items(detail: dict[str, Any]) -> str:
    return "".join(
        f'<div class="process-fact"><dt>{escape(item["label"])}</dt><dd>{escape(item["value"])}</dd></div>'
        for item in detail["facts"]
    )


def camera_process_items(detail: dict[str, Any]) -> str:
    cards = []
    for camera in detail["cameras"]:
        items = "".join(f"<li>{escape(item)}</li>" for item in camera["items"])
        cards.append(
            f'<article class="camera-process-card"><span>CAMERA {escape(camera["number"])}</span>'
            f'<h3>{escape(camera["title"])}</h3><ul>{items}</ul></article>'
        )
    return "".join(cards)


def inspection_detail_sections(detail: dict[str, Any]) -> str:
    sections = []
    for section in detail["inspectionSections"]:
        items = ""
        if section.get("items"):
            items = '<ul class="inspection-point-list">' + "".join(f"<li>{escape(item)}</li>" for item in section["items"]) + "</ul>"
        if section.get("images"):
            figures = []
            for image in section["images"]:
                figures.append(
                    f'<figure class="inspection-media"><img src="{escape(nested_asset(image["src"]))}" '
                    f'alt="{escape(image["alt"])}" loading="lazy" decoding="async">'
                    f'<figcaption>{escape(image["caption"])}</figcaption></figure>'
                )
            media = f'<div class="inspection-media-stack">{"".join(figures)}</div>'
        elif section.get("imageSrc"):
            media = (
                f'<figure class="inspection-media"><img src="{escape(nested_asset(section["imageSrc"]))}" '
                f'alt="{escape(section["imageAlt"])}" loading="lazy" decoding="async"><figcaption>{escape(section["imageCaption"])}</figcaption></figure>'
            )
        else:
            media = (
                f'<figure class="inspection-media is-placeholder" aria-label="{escape(section["imageAlt"])}">'
                f'<div><span>Image Area</span><strong>{escape(section["imageAlt"])}</strong>'
                f'<p>실제 검사 이미지 제공 후 삽입</p></div><figcaption>{escape(section["imageCaption"])}</figcaption></figure>'
            )
        reverse = " is-reversed" if section.get("imagePosition") == "right" else ""
        sections.append(
            f'<section class="process-inspection-section{reverse}" aria-labelledby="inspection-{escape(section["number"])}-heading">'
            f'<div class="case-study-inner process-inspection-grid">{media}<div class="process-inspection-copy">'
            f'<p class="case-story-index">{escape(section["number"])} · Inspection</p>'
            f'<h2 id="inspection-{escape(section["number"])}-heading">{escape(section["title"])}</h2>'
            f'{text_blocks(section["body"])}{items}</div></div></section>'
        )
    return "".join(sections)


def render_process_detail(case: dict[str, Any], template: str) -> str:
    detail = case["processDetail"]
    canonical = f"https://www.aspec-tech.co.kr/case-studies/{case['slug']}.html"
    title = case.get("seoTitle") or f"{case['title']} 구축사례 | ASPEC"
    meta_description = case.get("metaDescription") or case["summary"]
    og_image = case.get("ogImage") or case["heroImage"]
    if not re.match(r"^https?://", og_image):
        og_image = "https://www.aspec-tech.co.kr/" + og_image.lstrip("/")
    webpage = {
        "@context": "https://schema.org", "@type": "WebPage", "name": case.get("pageHeading") or case["title"],
        "description": meta_description, "url": canonical, "primaryImageOfPage": og_image,
        "publisher": {"@type": "Organization", "name": "ASPEC", "url": "https://www.aspec-tech.co.kr/"},
    }
    breadcrumb = {
        "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "홈", "item": "https://www.aspec-tech.co.kr/"},
            {"@type": "ListItem", "position": 2, "name": "구축사례", "item": "https://www.aspec-tech.co.kr/portfolio.html"},
            {"@type": "ListItem", "position": 3, "name": case["title"], "item": canonical},
        ],
    }
    challenges = "".join(f'<li>{escape(item.strip())}</li>' for item in re.split(r"\n+", case["difficulty"]) if item.strip())
    speed_items = "".join(f'<li>{escape(item)}</li>' for item in detail["speed"]["items"])
    result_cards = "".join(
        f'<article class="result-card"><h3>{escape(item["title"])}</h3><p>{escape(item["body"])}</p></article>'
        for item in detail["resultCards"]
    )
    result_details = "".join(f'<li>{escape(item)}</li>' for item in case["results"])
    engineering_items = "".join(f'<li>{escape(item)}</li>' for item in detail["engineeringItems"])
    technology_links = "".join(
        f'<a href="{escape(item["url"])}">{escape(item["name"])}</a>' for item in case["relatedProducts"]
    )
    replacements = {
        "TITLE": title, "META_DESCRIPTION": meta_description, "CANONICAL": canonical, "OG_IMAGE": og_image,
        "WEBPAGE_JSON_LD": json.dumps(webpage, ensure_ascii=False, separators=(",", ":")),
        "BREADCRUMB_JSON_LD": json.dumps(breadcrumb, ensure_ascii=False, separators=(",", ":")),
        "CATEGORY_LABEL": case["categoryLabel"], "CASE_TITLE": case["title"],
        "PAGE_HEADING": case.get("pageHeading") or case["title"], "HERO_SUBHEADING": detail["heroSubheading"],
        "HERO_DESCRIPTION": detail["heroDescription"], "HERO_IMAGE": nested_asset(case["heroImage"]),
        "HERO_IMAGE_ALT": case.get("heroImageAlt") or case["title"],
        "HERO_IMAGE_CAPTION": case.get("heroImageCaption") or case["title"],
        "PROCESS_FACTS": process_fact_items(detail), "OVERVIEW": text_blocks(case["overview"]),
        "PROBLEM": text_blocks(case["problem"]), "CHALLENGES": challenges,
        "SOLUTION": text_blocks(case["solution"]), "CAMERA_PROCESS": camera_process_items(detail),
        "INSPECTION_SECTIONS": inspection_detail_sections(detail),
        "SPEED_TITLE": detail["speed"]["title"], "SPEED_BODY": text_blocks(detail["speed"]["body"]),
        "SPEED_ITEMS": speed_items, "RESULT_CARDS": result_cards, "RESULT_DETAILS": result_details,
        "ENGINEERING_INTRO": text_blocks(detail["engineeringIntro"]), "ENGINEERING_ITEMS": engineering_items,
        "TECHNOLOGY_LINKS": technology_links, "CTA_TITLE": detail["cta"]["title"],
        "CTA_BODY": detail["cta"]["body"], "CTA_LABEL": detail["cta"]["label"], "CTA_URL": detail["cta"]["url"],
    }
    output = template
    escaped_tokens = {"TITLE", "META_DESCRIPTION", "CANONICAL", "OG_IMAGE", "CATEGORY_LABEL", "CASE_TITLE", "PAGE_HEADING", "HERO_SUBHEADING", "HERO_DESCRIPTION", "HERO_IMAGE", "HERO_IMAGE_ALT", "HERO_IMAGE_CAPTION", "SPEED_TITLE", "CTA_TITLE", "CTA_BODY", "CTA_LABEL", "CTA_URL"}
    for key, value in replacements.items():
        output = output.replace("{{" + key + "}}", escape(value) if key in escaped_tokens else value)
    if re.search(r"{{[A-Z0-9_]+}}", output):
        raise BuildError(f"Unresolved process template token for {case['slug']}")
    return GENERATED_MARKER + "\n" + output


def render_detail(case: dict[str, Any], lookup: dict[str, dict[str, Any]], template: str) -> str:
    canonical = f"https://www.aspec-tech.co.kr/case-studies/{case['slug']}.html"
    title = f"{case['title']} 구축사례 | ASPEC"
    meta_description = case.get("metaDescription") or case["summary"]
    og_image = case.get("ogImage") or case["heroImage"]
    if not re.match(r"^https?://", og_image):
        og_image = "https://www.aspec-tech.co.kr/" + og_image.lstrip("/")

    webpage = {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": case["title"],
        "description": meta_description,
        "url": canonical,
        "primaryImageOfPage": og_image,
        "publisher": {"@type": "Organization", "name": "ASPEC", "url": "https://www.aspec-tech.co.kr/"},
    }
    breadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "홈", "item": "https://www.aspec-tech.co.kr/"},
            {"@type": "ListItem", "position": 2, "name": "구축사례", "item": "https://www.aspec-tech.co.kr/portfolio.html"},
            {"@type": "ListItem", "position": 3, "name": case["categoryLabel"], "item": f"https://www.aspec-tech.co.kr/portfolio.html?category={case['category']}"},
            {"@type": "ListItem", "position": 4, "name": case["title"], "item": canonical},
        ],
    }
    difficulty = "".join(f'<div class="problem-point">{escape(item.strip())}</div>' for item in re.split(r"\n+", case["difficulty"]) if item.strip())
    replacements = {
        "TITLE": title,
        "META_DESCRIPTION": meta_description,
        "CANONICAL": canonical,
        "OG_TITLE": title,
        "OG_DESCRIPTION": meta_description,
        "OG_IMAGE": og_image,
        "WEBPAGE_JSON_LD": json.dumps(webpage, ensure_ascii=False, separators=(",", ":")),
        "BREADCRUMB_JSON_LD": json.dumps(breadcrumb, ensure_ascii=False, separators=(",", ":")),
        "CATEGORY": case["category"],
        "CATEGORY_LABEL": case["categoryLabel"],
        "CASE_TITLE": case["title"],
        "SUMMARY": case["summary"],
        "HERO_IMAGE": nested_asset(case["heroImage"]),
        "HERO_IMAGE_ALT": case.get("heroImageAlt") or case["title"],
        "PROJECT_SUMMARY_ITEMS": summary_items(case),
        "OVERVIEW": text_blocks(case["overview"]),
        "PROBLEM": text_blocks(case["problem"]),
        "DIFFICULTY_ITEMS": difficulty,
        "SOLUTION": text_blocks(case["solution"]),
        "SYSTEM_ITEMS": system_items(case),
        "INSPECTION_METHOD": text_blocks(case["inspectionMethod"]),
        "PROCESS_ITEMS": process_items(case["inspectionMethod"]),
        "GALLERY_SECTION": gallery_section(case),
        "RESULTS_SECTION": results_section(case),
        "TECHNOLOGY_ITEMS": technology_items(case),
        "RELATED_CASES_SECTION": related_cases_section(case, lookup),
    }
    output = template.replace('<meta name="robots" content="noindex, nofollow">', '<meta name="robots" content="index, follow">')
    for key, value in replacements.items():
        output = output.replace("{{" + key + "}}", escape(value) if key in {"TITLE", "META_DESCRIPTION", "CANONICAL", "OG_TITLE", "OG_DESCRIPTION", "OG_IMAGE", "CATEGORY", "CATEGORY_LABEL", "CASE_TITLE", "SUMMARY", "HERO_IMAGE", "HERO_IMAGE_ALT"} else value)
    if re.search(r"{{[A-Z0-9_]+}}", output):
        raise BuildError(f"Unresolved template token for {case['slug']}")
    return GENERATED_MARKER + "\n" + output


def expected_detail_pages(cases: list[dict[str, Any]]) -> dict[Path, str]:
    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    process_template = PROCESS_TEMPLATE_PATH.read_text(encoding="utf-8")
    lookup = {case["slug"]: case for case in cases}
    pages: dict[Path, str] = {}
    for case in cases:
        if not case["published"]:
            continue
        selected = case.get("detailTemplate", "default")
        content = render_process_detail(case, process_template) if selected == "process" else render_detail(case, lookup, template)
        pages[OUTPUT_DIR / f"{case['slug']}.html"] = content
    return pages


def build_sitemap(cases: list[dict[str, Any]]) -> str:
    content, newline = read_preserving_newlines(SITEMAP_PATH)
    published = [case for case in cases if case["published"]]
    pattern = re.compile(r"\s*" + re.escape(SITEMAP_START) + r".*?" + re.escape(SITEMAP_END), re.DOTALL)
    if not published:
        return pattern.sub("", content, count=1) if pattern.search(content) else content

    rows = [SITEMAP_START]
    for case in published:
        rows.append(f'  <url><loc>https://www.aspec-tech.co.kr/case-studies/{case["slug"]}.html</loc><priority>0.8</priority></url>')
    rows.append(SITEMAP_END)
    block = newline + newline.join(rows)
    if pattern.search(content):
        return pattern.sub(block, content, count=1)
    return content.replace("</urlset>", block + newline + "</urlset>")


def check_or_write(path: Path, expected: str, check: bool, changes: list[str]) -> None:
    current = read_preserving_newlines(path)[0] if path.exists() else None
    if current == expected:
        return
    changes.append(str(path.relative_to(ROOT)))
    if not check:
        write_preserving_newlines(path, expected)


def remove_stale_generated(expected: set[Path], check: bool, changes: list[str]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in OUTPUT_DIR.glob("*.html"):
        if path in expected:
            continue
        content = path.read_text(encoding="utf-8", errors="replace")
        if content.startswith(GENERATED_MARKER):
            changes.append(str(path.relative_to(ROOT)))
            if not check:
                path.unlink()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate and report files that would change")
    args = parser.parse_args()

    try:
        cases = load_cases()
        changes: list[str] = []
        check_or_write(PORTFOLIO_PATH, build_portfolio(cases), args.check, changes)

        detail_pages = expected_detail_pages(cases)
        for path, content in detail_pages.items():
            check_or_write(path, content, args.check, changes)
        remove_stale_generated(set(detail_pages), args.check, changes)
        check_or_write(SITEMAP_PATH, build_sitemap(cases), args.check, changes)
    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    published_count = sum(1 for case in cases if case["published"])
    print(f"cases={len(cases)} published={published_count} detail_pages={len(detail_pages)}")
    if changes:
        verb = "would change" if args.check else "changed"
        print(f"{verb}: " + ", ".join(changes))
        return 1 if args.check else 0
    print("changed: none")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
